apiVersion: v1
kind: Service
metadata:
  name: plumtalks-backend
  namespace: plumtalks
spec:
  selector:
    app: plumtalks-backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP

